use std::time::Instant;

/**
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
pub fn project_euler_2() {
    let start = Instant::now();
    let mut prev1: i32 = 1;
    let mut prev2: i32 = 2;
    let mut total: i32 = 2;

    let mut current: i32;

    loop {
        current = prev1 + prev2;
        if current >= 4000000 {
            break;
        }

        if current % 2 == 0 {
            total += current;
        }

        prev1 = prev2;
        prev2 = current;
    }

    println!("Project Euler 2: {}, Time Taken: {}", total, start.elapsed().as_secs());
}